---
- hosts: all
  roles:
    - role: geerlingguy.mysql
      become: yes
      vars:
        mysql_user_home: '~'
        mysql_user_name: '{{ ansible_user_id }}'
        mysql_user_password: ''
        mysql_databases:
          - name: '{{ project }}'
        mysql_packages:
          - mariadb-client
          - mariadb-server
          - python-mysqldb
