---
- hosts: all
  vars:
    php_packages_extra:
      - php{{ php_version }}-intl
      - php{{ php_version }}-mysql
      - php{{ php_version }}-zip
      - php-memcached
      - php-imagick
      - php-phalcon
    php_webserver_daemon: "nginx"
    php_install_recommends: no
    php_enable_php_fpm: yes
    php_fpm_listen: /var/run/php-fpm.sock
    php_use_managed_ini: true
    php_fpm_pool_user: "coaster"
    php_fpm_pool_group: "coaster"
    php_date_timezone: "Asia/Jakarta"
    php_expose_php: "Off"
    php_enable_apc: true

  roles:
    - role: geerlingguy.php-versions
      become: yes
    - role: geerlingguy.php
      become: yes
      vars:
    - role: geerlingguy.composer
      become: yes
      vars:
        composer_global_packages:
          - name: fxp/composer-asset-plugin
  tasks:
    - name: 'install package dependencies'
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - jpegoptim
        - optipng
        - pngquant
        - unzip
        - jq
      become: yes