---
- hosts: all
  vars_files:
    - ../secret.yml
  vars:
    query: "[?name == '{{ project }}.dev' ]|[0]"
    nginx_vhosts:
      - template: '{{ playbook_dir }}/../assets/nginx/yii-advanced.j2'
        project: '{{ project }}'
        server_name: '{{ project }}.dev.rollingglory.com'
  roles:
    - role: geerlingguy.nginx
      become: yes
    - role: geerlingguy.mysql
      become: yes
      vars:
        mysql_user_home: '~'
        mysql_user_name: '{{ ansible_user_id }}'
        mysql_user_password: ''
        mysql_databases:
          - name: '{{ project }}'
        mysql_packages:
          - mariadb-client
          - mariadb-server
          - python-mysqldb
  tasks:
    - name: 'clone project'
      git:
        repo: https://{{ bb }}@bitbucket.org/rollingglory/{{ repo }}
        dest: ~/{{ project }}
        accept_hostkey: yes

    - name: 'install composer dependencies'
      command: composer install
      args:
        chdir: ~/{{ project }}

    - name: 'init yii'
      command: php init --env=Development --overwrite=n
      args:
        chdir: ~/{{ project }}

    - name: 'create backend symlink'
      file:
        path: ~/{{ project }}/frontend/web/admin
        src: ../../backend/web
        state: link

    - name: 'apply vendor patch'
      command: cp -r ~/{{ project }}/update-vendor/vendor ~/{{ project }}
      notify: reload nginx

    - name: 'check if record exist'
      local_action:
        module: command
        args: doctl compute domain records list rollingglory.com -o json
      register: records

    - set_fact:
        record: '{{ records.stdout | from_json | json_query(query) }}'

    - name: 'modify record if exist and different'
      local_action:
        module: command
        args: doctl compute domain records update rollingglory.com --record-id {{ record.id }} --record-data {{ inventory_hostname.split("@")[-1] }}.
      when: record and record.data != inventory_hostname.split("@")[-1]

    - name: 'add record if not exist'
      local_action:
        module: command
        args: doctl compute domain records create rollingglory.com --record-type CNAME --record-name {{ project }}.dev --record-data {{ inventory_hostname.split("@")[-1] }}.
      when: not record