---
- hosts: all
  vars:
    php_version: '7.2'
  roles:
    - role: geerlingguy.nginx
      become: yes
    - role: geerlingguy.php_versions
      become: yes
    - role: geerlingguy.php
      become: yes
      vars:
        php_packages_extra:
          - php{{ php_version }}-intl
          - php{{ php_version }}-mysql
          - php{{ php_version }}-odbc
          - php{{ php_version }}-pgsql
        php_enable_php_fpm: true
        php_fpm_listen: /var/run/php-fpm.sock
    - role: geerlingguy.composer
      become: yes
      vars:
        composer_global_packages:
          - name: fxp/composer-asset-plugin
    - role: geerlingguy.mysql
      become: yes
      vars:
        mysql_user_home: '~'
        mysql_user_name: '{{ ansible_user_id }}'
        mysql_user_password: ''
        mysql_databases:
          - name: db
        mysql_packages:
          - mariadb-client
          - mariadb-server
          - python-mysqldb
  tasks:
    - name: 'install package dependencies'
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - jpegoptim
        - optipng
        - pngquant
      become: yes
    - name: 'clone project'
      git:
        repo: git@bitbucket.org:rollingglory/{{ project }}
        dest: ~/app
        accept_hostkey: yes
    - name: 'install composer dependencies'
      command: composer install
      args:
        chdir: ~/app
    - name: 'initialize database schema'
      mysql_db:
        state: import
        name: db
        target: ~/app/db/schema.sql
    - name: 'initialize database data'
      mysql_db:
        state: import
        name: db
        target: ~/app/db/data.sql
    - name: 'init yii'
      command: php init --env=Development --overwrite=n
      args:
        chdir: ~/app
