---
- hosts: all
  vars:
    php_packages_extra:
      - php-intl
      - php-mysql
      - php-zip
    php_webserver_daemon: "nginx"
    php_install_recommends: no
    php_enable_php_fpm: yes
    php_fpm_listen: /var/run/php-fpm.sock
    php_use_managed_ini: true
    php_fpm_pool_user: "coaster"
    php_fpm_pool_group: "coaster"
    php_date_timezone: "Asia/Jakarta"

    nginx_vhosts:
      - template: '{{ playbook_dir }}/../assets/nginx/vhost.j2'
        project: '{{ project }}'
        server_name: '{{ project }}.dev.rollingglory.com'
  roles:
    - role: geerlingguy.nginx
      become: yes
    - role: geerlingguy.php-versions
      become: yes
    - role: geerlingguy.php
      become: yes
      vars:
    - role: geerlingguy.composer
      become: yes
      vars:
        composer_global_packages:
          - name: fxp/composer-asset-plugin
    - role: geerlingguy.mysql
      become: yes
      vars:
        mysql_user_home: '~'
        mysql_user_name: '{{ ansible_user_id }}'
        mysql_user_password: ''
        mysql_databases:
          - name: '{{ project }}'
        mysql_packages:
          - mariadb-client
          - mariadb-server
          - python-mysqldb
  tasks:
    - name: 'install package dependencies'
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - jpegoptim
        - optipng
        - pngquant
      become: yes

    - name: 'clone project'
      git:
        repo: https://***REMOVED***@bitbucket.org/rollingglory/{{ repo }}
        dest: ~/{{ project }}
        accept_hostkey: yes

    - name: 'install composer dependencies'
      command: composer install
      args:
        chdir: ~/{{ project }}

    - name: 'init yii'
      command: php init --env=Development --overwrite=n
      args:
        chdir: ~/{{ project }}
